/**
 * Message type constants for Chrome extension communication
 * Prevents magic strings and provides type safety
 */

export const MessageTypes = {
  // Configuration messages
  GET_CONFIG: 'GET_CONFIG',
  UPDATE_CONFIG: 'UPDATE_CONFIG',
  GET_CONNECTION_MANAGER_STATS: 'GET_CONNECTION_MANAGER_STATS',
  
  // Connection management messages
  CLONE_CONNECTION: 'CLONE_CONNECTION',
  CREATE_PERSISTENT_CONNECTION: 'CREATE_PERSISTENT_CONNECTION',
  GET_MANAGED_CONNECTIONS: 'GET_MANAGED_CONNECTIONS',
  CLOSE_MANAGED_CONNECTION: 'CLOSE_MANAGED_CONNECTION',
  REMOVE_MANAGED_CONNECTION: 'REMOVE_MANAGED_CONNECTION',
  CLOSE_ALL_MANAGED_CONNECTIONS: 'CLOSE_ALL_MANAGED_CONNECTIONS',
  REMOVE_ALL_MANAGED_CONNECTIONS: 'REMOVE_ALL_MANAGED_CONNECTIONS',
  
  // Response messages
  CONFIG_UPDATE: 'CONFIG_UPDATE',
  CONNECTION_MANAGER_STATS: 'CONNECTION_MANAGER_STATS',
  CONNECTION_CLONED: 'CONNECTION_CLONED',
  PERSISTENT_CONNECTION_CREATED: 'PERSISTENT_CONNECTION_CREATED',
  MANAGED_CONNECTIONS: 'MANAGED_CONNECTIONS',
  MANAGED_CONNECTION_CLOSED: 'MANAGED_CONNECTION_CLOSED',
  MANAGED_CONNECTION_REMOVED: 'MANAGED_CONNECTION_REMOVED',
  ALL_MANAGED_CONNECTIONS_CLOSED: 'ALL_MANAGED_CONNECTIONS_CLOSED',
  ALL_MANAGED_CONNECTIONS_REMOVED: 'ALL_MANAGED_CONNECTIONS_REMOVED',
  
  // Log messages
  LOG_ENTRY: 'LOG_ENTRY',
  
  // Injected script messages
  CLONE_CONNECTION_REQUEST: 'CLONE_CONNECTION_REQUEST',
  
  // Core messages
  GET_STATS: 'GET_STATS',
  TOGGLE_DEBUG: 'TOGGLE_DEBUG',
  TOGGLE_MASTER: 'TOGGLE_MASTER',
  RAW_DATA_EVENT: 'RAW_DATA_EVENT'
} as const;

export type MessageType = typeof MessageTypes[keyof typeof MessageTypes];
